revert

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,8 +4,6 @@ on:
   push:
     tags:
       - "v*"
-    branches:
-      - ci  # TODO
 
 permissions:
   contents: write
@@ -64,39 +62,39 @@ jobs:
           BLENDER_EXE: 'blender'
         run: just test-blender
 
-#  build-and-release: TODO
-#    needs: test
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v5
-#
-#      - name: Set output for version name
-#        id: version
-#        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
-#
-#      - name: Verify Manifest Version
-#        run: |
-#          TAG_VERSION=${GITHUB_REF#refs/tags/}
-#          TAG_VERSION=${TAG_VERSION#v}
-#          MANIFEST_VERSION=$(grep -m 1 "^version =" savepoints/blender_manifest.toml | cut -d '"' -f 2)
-#
-#          echo "Tag Version: $TAG_VERSION"
-#          echo "Manifest Version: $MANIFEST_VERSION"
-#
-#          if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
-#            echo "::error::Version mismatch! Tag says '$TAG_VERSION' but manifest says '$MANIFEST_VERSION'"
-#            exit 1
-#          fi
-#
-#      - name: Create Zip File
-#        run: |
-#          zip -r ./savepoints_${{ steps.version.outputs.TAG_NAME }}.zip savepoints -x "*.pyc" -x "*__pycache__*"
-#
-#      - name: Create GitHub Release
-#        uses: softprops/action-gh-release@v2
-#        with:
-#          files: savepoints_${{ steps.version.outputs.TAG_NAME }}.zip
-##          generate_release_notes: true
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  build-and-release:
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5
+
+      - name: Set output for version name
+        id: version
+        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
+
+      - name: Verify Manifest Version
+        run: |
+          TAG_VERSION=${GITHUB_REF#refs/tags/}
+          TAG_VERSION=${TAG_VERSION#v}
+          MANIFEST_VERSION=$(grep -m 1 "^version =" savepoints/blender_manifest.toml | cut -d '"' -f 2)
+
+          echo "Tag Version: $TAG_VERSION"
+          echo "Manifest Version: $MANIFEST_VERSION"
+
+          if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
+            echo "::error::Version mismatch! Tag says '$TAG_VERSION' but manifest says '$MANIFEST_VERSION'"
+            exit 1
+          fi
+
+      - name: Create Zip File
+        run: |
+          zip -r ./savepoints_${{ steps.version.outputs.TAG_NAME }}.zip savepoints -x "*.pyc" -x "*__pycache__*"
+
+      - name: Create GitHub Release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: savepoints_${{ steps.version.outputs.TAG_NAME }}.zip
+#          generate_release_notes: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
